### ISSUE TITLE
ora.sh manually input chatbot id

### ISSUE THREAD

**Issue by kwekewk** [xtekky/openai-gpt4#16]
Maybe we can use their gpt-4 template model by manually using chatbotid before they release it. And ability indexing and use created chatbot from log. And generate art feature?.

**Comment by xtekky** [comment]
can you please elaborate ?
and their gpt4 model should only be available per subscription no ?

**Comment by kwekewk** [comment]
> can you please elaborate ? and their gpt4 model should only be available per subscription no ?

im talking about allowing input chatbotid from user/files . As curently the code only accept botid generated from CompletionModel(?). i've tried their gpt4 model with random userid, it allow nonregistered user access gpt4

**Comment by xtekky** [comment]
i will check it tomorrow, I didn't really deep the reversing of the site but I am definitely intrigued that u can use gpt-4 !!, would you please give more instructions on how to get to use it from their site

**Comment by kwekewk** [comment]
> i will check it tomorrow, I didn't really deep the reversing of the site but I am definitely intrigued that u can use gpt-4 !!, would you please give more instructions on how to get to use it from their site

the code is messy and cant  continue conversation
https://github.com/kwekewk/openai-gpt4/commit/3d7dd87eaa5316ad9fedb31521876f876b14502b

from vanilla gpt4 template
https://github.com/kwekewk/openai-gpt4/blob/main/nora.py

error messg
`
**Answer: (a) Yes; Colonel Mustard was in the observatory with the candlestick**
>>> thx
{'error': {'message': 'Invalid status code: P2025', 'err': {'code': 'ERR_HTTP_INVALID_STATUS_CODE'}}, 'status': 500}
Error: {'message': 'Invalid status code: P2025', 'err': {'code': 'ERR_HTTP_INVALID_STATUS_CODE'}}
Traceback (most recent call last):
  File "/home/punchbag/openai-gpt4/nora.py", line 26, in <module>
    print(response.completion.choices[0].text)
AttributeError: 'NoneType' object has no attribute 'completion'
`

**Comment by dayerqq** [comment]
In fact, this is useless as GPT4 is bound to a user ID, and it must be a registered user ID, not randomly generated.

Due to high demand free GPT-4 usage is currently limited to 10 messages per day.
These are the IDs for all GPT4 robots：["fbe53266-673c-4b70-9d2d-d247785ccd91", "bd5781cf-727a-45e9-80fd-a3cfce1350c6", "993a0102-d397-47f6-98c3-2587f2c9ec3a", "ae5c524e-d025-478b-ad46-8843a5745261", "cc510743-e4ab-485e-9191-76960ecb6040", "a5cd2481-8e24-4938-aa25-8e26d6233390", "6bca5930-2aa1-4bf4-96a7-bea4d32dcdac", "884a5f2b-47a2-47a5-9e0f-851bbe76b57c", "d5f3c491-0e74-4ef7-bdca-b7d27c59e6b3", "d72e83f6-ef4e-4702-844f-cf4bd432eef7", "6e80b170-11ed-4f1a-b992-fd04d7a9e78c", "8ef52d68-1b01-466f-bfbf-f25c13ff4a72", "d0674e11-f22e-406b-98bc-c1ba8564f749", "a051381d-6530-463f-be68-020afddf6a8f", "b8b12eaa-5d47-44d3-92a6-4d706f2bcacf", "99c0afa1-9e32-4566-8909-f4ef9ac06226", "1be65282-9c59-4a96-99f8-d225059d9001", "dba16bd8-5785-4248-a8e9-b5d1ecbfdd60", "1731450d-3226-42d0-b41c-4129fe009524", "8e74635d-000e-4819-ab2c-4e986b7a0f48", "afe7ed01-c1ac-4129-9c71-2ca7f3800b30", "e374c37a-8c44-4f0e-9e9f-1ad4609f24f5"];
Everyone can see if they can find the real registered user ID through the API.

**Comment by kwekewk** [comment]
> 

I don't know, I use simple api wrapper. It can connect even using random uuid. Well, even if gpt4 limited, the purpose is we can index createdbot to files and input chatbotid

**Comment by xtekky** [comment]
got it, will update api whenever I get the chance to

**Comment by xtekky** [comment]
solved
